### ISSUE TITLE
Is safe to use?

### ISSUE THREAD

**Issue by Ganondorf91** [PsykoDev/Redirect#2]
Is this mod and the teleport one safe to use? I remember the first days of the transfer I got banned and last thing I did before went to relog to find out I was banned, was use the teleport mod but I was also doing ace dungeons with the redirect mod.. so I'm not sure if was just one of them or both that got me banned :/ I wanna use it again but I wanna be sure of this first if possible.

**Comment by PsykoDev** [comment]
you can, i use this mod since 1 year all day and i'm always in game without probleme

**Comment by Ganondorf91** [comment]
Ok nice, will use it again then... but what about this one? https://github.com/PsykoDev/Teleport

**Comment by PsykoDev** [comment]
Teleport can crash you game if you spam but you can yeah
